[package]
name = "solver-cpu"
authors = ["johncantrell97"]

version.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
bitcoin.workspace = true
bitcoin-wallet.workspace = true
sha2 = "0.8.2"
rayon = "1.3.0"
ring = "0.16"
