[package]
name = "solver-gpu"

version.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin.workspace = true
bitcoin-wallet.workspace = true
sha2 = "0.8.2"
rayon = "1.3.0"
ring = "0.16"

ocl = "0.19"
hex = "0.3.1"
reqwest = { version = "0.10.6", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
